# Example karka configuration

site_name = "Example site"
base_url = "https://www.example.com"
verbose = false
include_drafts = false
ignore = ".karkaignore"

[[authors]]
name = "Your name here"
email = "name@example.com"
fediverse = "name@example.social"

[dirs]
assets = "_assets"
data = "_data"
schemas = "_schemas"
templates = "_templates"
pages = "pages"
content = "content"
output = "dist"

# [i18n]
# input = "frontmatter"
# output = "subdir_except_default"
# default = "en"
# languages = ["en"]
